Repository ruifm/gitlinker.nvim, pull requests merged in 2021-04, with the labels that each got.

#4 fix: uri parsing (closes #2)
  lua/gitlinker.lua
  lua/gitlinker/git.lua
Labels: bug

#5 Add CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
Labels: doc

#7 doc: add pull request template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: doc

#8 doc: add FUNDING.yml
  .github/FUNDING.yml
Labels: doc

#9 Added option to disable printing url
  README.md
  lua/gitlinker.lua
  lua/gitlinker/opts.lua
Labels: enhancement

#11 Fix description for `mappings` in option
  README.md
  doc/gitlinker.txt
Labels: doc

#13 Extract port from uri
  README.md
  doc/gitlinker.txt
  lua/gitlinker.lua
  lua/gitlinker/git.lua
  lua/gitlinker/hosts.lua
Labels: bug
